//
//  state_helper.swift
//  Project 2
//
//  Created by Gabriela Garcia on 11/6/19.
//  Copyright © 2019 Gabriela Garcia. All rights reserved.
//

struct state_helper {
       
       let states = ["Alaska",
                   "Alabama",
                   "Arkansas",
                   "Arizona",
                   "California",
                   "Colorado",
                   "Connecticut",
                   "Delaware",
                   "Florida",
                   "Georgia",
                   "Hawaii",
                   "Iowa",
                   "Idaho",
                   "Illinois",
                   "Indiana",
                   "Kansas",
                   "Kentucky",
                   "Louisiana",
                   "Massachusetts",
                   "Maryland",
                   "Maine",
                   "Michigan",
                   "Minnesota",
                   "Missouri",
                   "Mississippi",
                   "Montana",
                   "North Carolina",
                   "North Dakota",
                   "Nebraska",
                   "New Hampshire",
                   "New Jersey",
                   "New Mexico",
                   "Nevada",
                   "New York",
                   "Ohio",
                   "Oklahoma",
                   "Oregon",
                   "Pennsylvania",
                   "Rhode Island",
                   "South Carolina",
                   "South Dakota",
                   "Tennessee",
                   "Texas",
                   "Utah",
                   "Virginia",
                   "Vermont",
                   "Washington",
                   "Wisconsin",
                   "West Virginia",
                   "Wyoming"]
       
      let capitals = ["Alabama": "Montgomery",
                   "Alaska": "Juneau",
                   "Arizona":"Phoenix",
                   "Arkansas":"Little Rock",
                   "California": "Sacramento",
                   "Colorado":"Denver",
                   "Connecticut":"Hartford",
                   "Delaware":"Dover",
                   "Florida": "Tallahassee",
                   "Georgia": "Atlanta",
                   "Hawaii": "Honolulu",
                   "Idaho": "Boise",
                   "Illinios": "Springfield",
                   "Indiana": "Indianapolis",
                   "Iowa": "Des Moines",
                   "Kansas": "Topeka",
                   "Kentucky": "Frankfort",
                   "Louisiana": "Baton Rouge",
                   "Maine": "Augusta",
                   "Maryland": "Annapolis",
                   "Massachusetts": "Boston",
                   "Michigan": "Lansing",
                   "Minnesota": "St. Paul",
                   "Mississippi": "Jackson",
                   "Missouri": "Jefferson City",
                   "Montana": "Helena",
                   "Nebraska": "Lincoln",
                   "Neveda": "Carson City",
                   "New Hampshire": "Concord",
                   "New Jersey": "Trenton",
                   "New Mexico": "Santa Fe",
                   "New York": "Albany",
                   "North Carolina": "Raleigh",
                   "North Dakota": "Bismarck",
                   "Ohio": "Columbus",
                   "Oklahoma": "Oklahoma City",
                   "Oregon": "Salem",
                   "Pennsylvania": "Harrisburg",
                   "Rhoda Island": "Providence",
                   "South Carolina": "Columbia",
                   "South Dakoda": "Pierre",
                   "Tennessee": "Nashville",
                   "Texas": "Austin",
                   "Utah": "Salt Lake City",
                   "Vermont": "Montpelier",
                   "Virginia": "Richmond",
                   "Washington": "Olympia",
                   "West Virginia": "Charleston",
                   "Wisconsin": "Madison",
                   "Wyoming": "Cheyenne" ]
   }
